#+title: Gentoo emacs config files
#+author: Vincent Bailly


** Definitions

The following words or expression will have the following definition
for the scope of this document.

- "repo": git repository
- "remote repo": git repository hosted on GitHub
- "local repo": git repository hosted on your computer
- "GH": GitHub.com

** Assumptions

*** Remote repo

You are the owner of the remote repo and you push to it from only one
local repo.

*** Git and GH setup

You have git installed locally and you have already setup local GitHub
authentication. For example you have registered in GH your SSH local key.

*** Linux

All the commands are run in a Linux environment.

*** Bash

Default shell is bash, and all commands are run in a bash session.
To check default shell: ~echo $SHELL~
To check current shell: ~echo $0~

*** emacs config file

Emacs configuration file is ~$HOME/.emacs.d/init.el~

** Setup

*** Cloning the repository

The bash variables can be

#+begin_src bash

  export emacsConfigRemoteRepo='git@github.com:VincentBailly/gentoo-emacs-config.git'
  export emacsConfigLocalRepo="$HOME/gentooEmacsConfig"
  echo "export emacsConfigRemoteRepo=$emacsConfigRemoteRepo" >> $HOME/.bashrc
  echo "export emacsConfigLocalRepo=$emacsConfigLocalRepo" >> $HOME/.bashrc

  git clone $emacsConfigRemoteRepo $emacsConfigLocalRepo

#+end_src

*** Tangling config.org

In emacs

- open ~$emacsConfigLocalRepo/config.org~
- run ~M-x org-babel-tangle~, this will create config.el in the emacs folder.
- add the following line to the emacs config file: ~(load "~/.emacs.d/config.el")~
- restart emacs
